In [15]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
data = load_diabetes()

In [10]:
X = data['data']

In [12]:
X.shape

(442, 10)

In [39]:
X[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [11]:
Y = data['target']

In [13]:
Y.shape

(442,)

In [40]:
Y[0]

151.0

In [26]:
data['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [16]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [17]:
X_train.shape

(353, 10)

In [18]:
X_test.shape

(89, 10)

In [19]:
linear = LinearRegression()

In [20]:
linear.fit(X_train,Y_train)

LinearRegression()

In [21]:
y_pred = linear.predict(X_test) 

In [22]:
from sklearn.metrics import r2_score
r2_score(Y_test , y_pred)

0.4399387660024644

In [23]:
linear.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [24]:
linear.intercept_

151.88334520854633

# Making our own Linear Regression Class

In [29]:
# this is a general algo used in both higher dimension as well as lower dimension
class My_LR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
    
    def fit(self,X_train,Y_train):
        X_train = np.insert(X_train,0,1,axis=1) # 1st arg(Konse array me changes karna he)
#2nd arg(konse index me changes karne he) (3rd arg(konse se changes karne he yaha pe sari 1 values dalni he) 
        #4th arg(axis batat he jisme changes karna he) 
        # we need to calculate the inverse             
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(Y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    def predict(self,X_test):
      # we are doing (89,1) + betas[0]  (this (89,1) comes from comparing the shape of coef_ and X_test)
        y_pred = self.intercept_ + np.dot(X_test,self.coef_) # this can be done as they are matrix 
        return y_pred

In [35]:
LR.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [38]:
X_test[0]

array([ 0.06713621, -0.04464164,  0.00349435,  0.03564384,  0.0493413 ,
        0.03125356,  0.07072993, -0.03949338, -0.00060925,  0.01963284])

In [31]:
LR = My_LR()

In [32]:
LR.fit(X_train,Y_train)

In [36]:
y_pred = LR.predict(X_test)

In [37]:
r2_score(Y_test,y_pred)

0.4399387660024642

In [42]:
LR.intercept_

151.88334520854627