In [245]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [50]:
data = pd.read_csv(r"C:\Users\mynam\all the files for data science\Linear Regression from CampusX\placement.csv")

In [51]:
data.head()

cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [52]:
data = data.drop("placed",axis=1)

In [53]:
data.rename(columns = {"placement_exam_marks":"Packages"},inplace= True)

In [227]:
X = data.iloc[:,0:1]
Y = data.iloc[:,-1]

In [228]:
X_train ,X_test ,Y_train ,Y_test = train_test_split(X,Y,random_state=0)

In [229]:
X_train

cgpa
253  6.98
667  7.17
85   6.03
969  6.86
75   6.77
..    ...
835  6.67
192  6.67
629  8.15
559  6.61
684  8.02

[750 rows x 1 columns]

In [230]:
Y_train

253    76.0
667    54.0
85     28.0
969    41.0
75     56.0
       ... 
835    65.0
192    38.0
629    11.0
559    58.0
684    67.0
Name: Packages, Length: 750, dtype: float64

In [231]:
print(X_train.shape) 
print(Y_train.shape)

(750, 1)
(750,)


In [232]:
# using the linear Regression model of sklearn 
linear = LinearRegression()
linear.fit(X_train,Y_train)

LinearRegression()

In [233]:
linear.coef_

array([-0.94740055])

In [244]:
linear.intercept_

39.05415876492664

In [253]:
X_test.iloc[:,0].values[0]

6.73

In [273]:
Y_test

993    21.0
859    22.0
298    48.0
553    17.0
672    13.0
       ... 
462     9.0
356    50.0
2      40.0
478    36.0
695    11.0
Name: Packages, Length: 250, dtype: float64

In [235]:
y_pred = linear.predict(X_test)
y_pred

array([32.67815305, 32.87710716, 33.21817136, 31.98655064, 31.71180448,
       32.71604907, 32.86763316, 32.99079523, 32.55499098, 32.31814084,
       31.92970661, 32.15708274, 33.18974935, 32.69710106, 31.92970661,
       31.36126628, 31.89181059, 31.88233658, 31.5602204 , 32.32761484,
       31.79707053, 32.10971272, 33.78661169, 32.45077691, 31.49390236,
       32.85815915, 32.49814694, 32.95289921, 32.29919283, 31.98655064,
       32.73499708, 31.89181059, 31.42758432, 31.96760263, 31.66443446,
       32.55499098, 32.88658117, 32.63078302, 32.33708885, 33.36975545,
       32.30866683, 30.41386573, 32.71604907, 32.16655675, 32.9339512 ,
       33.15185332, 32.48867294, 32.24234879, 32.35603686, 31.87286258,
       33.25606738, 33.35080744, 32.24234879, 32.73499708, 33.33185943,
       32.37498487, 33.15185332, 32.61183501, 32.64025702, 31.92023261,
       32.34656285, 31.86338857, 31.79707053, 32.88658117, 32.75394509,
       32.15708274, 31.64548644, 32.4223549 , 33.14237932, 33.25

In [246]:
np.sqrt(metrics.mean_squared_error(Y_test ,y_pred))

19.017414241847273

In [275]:
# Now Building My own linear regression model (SIMPLE One)

class My_linear_reg:
    def __init__(self):
        self.m = None
        self.b = None
    def fit(self,x_train,y_train):
        num = 0
        n = 0
        deno = 0
        for i in range(x_train.shape[n]):
            num = num + (x_train[i]-x_train.mean())*(y_train[i]-y_train.mean())
            deno = deno +(x_train[i]-x_train.mean())**2
        self.m = num/deno
        self.b = (y_train.mean()) - (self.m*x_train.mean())
        print(self.m)
        print(self.b)
    def predict(self,x_test):
        l = []
        for i in range(x_test.shape[0]):
            l.append(x_test[i]*self.m + self.b)
        return l

In [276]:
x_test.shape[0]

250

In [277]:
range(x_train.shape[0])

range(0, 750)

In [278]:
x = data.iloc[:,0].values
y = data.iloc[:,-1].values

In [279]:
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,random_state=0)

In [280]:
x_train[0:9]

array([6.98, 7.17, 6.03, 6.86, 6.77, 7.5 , 7.57, 7.65, 7.97])

In [281]:
LE = My_linear_reg()

In [282]:
LE.fit(x_train,y_train)

-0.9474005524266186
39.05415876492667


In [283]:
LE.predict(x_test)[0]

32.67815304709553

In [284]:
y_test[0]

21.0